'use client'

import { useState } from 'react'
import { Activity, Archive, AudioLines, BatteryMedium, ChevronRight, Circle, Command, FileText, Headphones, MapPin, Menu, Mic, MoreHorizontal, Plus, Radio, Search, Shield, Signal, Sparkles, Timer, UserRound, Volume2, X } from 'lucide-react'

type CaseItem = { id: string; officer: string; title: string; location: string; status: 'ON SCENE' | 'STANDBY' | 'CLOSED'; updated: string; priority: string }

const caseList: CaseItem[] = [
  { id: 'CP-1048', officer: 'Mara Chen', title: 'North Harbor incident', location: 'North Harbor District', status: 'ON SCENE', updated: 'Live now', priority: 'HIGH' },
  { id: 'CP-1039', officer: 'D. Okafor', title: 'East Market theft', location: 'East Market', status: 'STANDBY', updated: '18m ago', priority: 'MED' },
  { id: 'CP-1021', officer: 'L. Alvarez', title: 'Ridgeway welfare check', location: 'Ridgeway', status: 'STANDBY', updated: '1h ago', priority: 'MED' },
  { id: 'CP-0998', officer: 'J. Whitaker', title: 'Kingston missing person', location: 'Kingston', status: 'CLOSED', updated: 'Yesterday', priority: 'LOW' },
]

const activity = [
  { time: '10:43:18', label: 'Voice session active', detail: 'Listening for officer input', icon: Mic, tone: 'live' as const },
  { time: '10:42:51', label: 'Scene brief retrieved', detail: '12 evidence items · 4 witness notes', icon: FileText, tone: 'default' as const },
  { time: '10:42:08', label: 'Route safety check', detail: 'North Harbor perimeter · clear', icon: MapPin, tone: 'default' as const },
  { time: '10:41:37', label: 'Timeline gap identified', detail: '21:40 — 22:15 · 35 minutes', icon: Timer, tone: 'amber' as const },
]

export default function Page() {
  const [selectedId, setSelectedId] = useState('CP-1048')
  const [listOpen, setListOpen] = useState(false)
  const [listening, setListening] = useState(true)
  const selected = caseList.find((item) => item.id === selectedId) ?? caseList[0]

  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="flex h-16 items-center justify-between border-b border-border/70 px-4 md:px-6">
        <div className="flex items-center gap-3"><button className="rounded-md p-2 hover:bg-muted md:hidden" onClick={() => setListOpen(!listOpen)} aria-label="Toggle case list">{listOpen ? <X size={18} /> : <Menu size={18} />}</button><div className="flex size-8 items-center justify-center rounded-md bg-primary text-primary-foreground"><Shield size={16} /></div><div><p className="font-mono text-[10px] font-bold tracking-[0.2em] text-muted-foreground">FIELDNOTE / VOICE</p><p className="text-xs text-muted-foreground">Officer field companion</p></div></div>
        <div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-full border border-border bg-card px-3 py-1.5 text-[11px] text-muted-foreground sm:flex"><Circle className="fill-emerald-500 text-emerald-500" size={7} /> eve agent online</div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Signal size={14} /><span className="hidden sm:inline">LTE · 84%</span><BatteryMedium size={17} /></div><div className="flex size-8 items-center justify-center rounded-full bg-muted"><UserRound size={15} /></div></div>
      </header>
      <div className="flex min-h-[calc(100vh-4rem)]">
        <aside className={`${listOpen ? 'fixed inset-y-16 left-0 z-30 flex w-[300px] shadow-xl' : 'hidden'} w-[300px] shrink-0 flex-col border-r border-border/70 bg-sidebar md:flex`}>
          <div className="border-b border-sidebar-border p-4"><div className="mb-4 flex items-center justify-between"><div><p className="font-mono text-[10px] font-bold tracking-[0.18em] text-sidebar-foreground/45">WORK / CASES</p><p className="mt-1 text-sm font-medium">{caseList.length} case channels</p></div><button className="rounded-md border border-sidebar-border p-1.5 text-sidebar-foreground/70 hover:bg-sidebar-accent" aria-label="New case"><Plus size={16} /></button></div><label className="flex items-center gap-2 rounded-md border border-sidebar-border bg-sidebar-accent/50 px-2.5 py-2"><Search size={14} className="text-sidebar-foreground/50" /><input className="w-full bg-transparent text-xs outline-none placeholder:text-sidebar-foreground/40" placeholder="Find a case" /></label></div>
          <div className="flex-1 overflow-y-auto p-2">{caseList.map((item) => <button key={item.id} onClick={() => { setSelectedId(item.id); setListOpen(false) }} className={`w-full rounded-md border p-3 text-left transition ${item.id === selected.id ? 'border-sidebar-primary/25 bg-sidebar-accent' : 'border-transparent hover:bg-sidebar-accent/60'}`}><div className="mb-2 flex items-center justify-between"><span className="font-mono text-[10px] font-bold tracking-wider text-sidebar-foreground/45">{item.id}</span><span className={`flex items-center gap-1.5 text-[9px] font-bold tracking-wider ${item.status === 'ON SCENE' ? 'text-emerald-600' : item.status === 'CLOSED' ? 'text-sidebar-foreground/40' : 'text-amber-600'}`}>{item.status === 'ON SCENE' && <Circle className="fill-current" size={6} />}{item.status}</span></div><p className="text-sm font-medium text-sidebar-foreground">{item.title}</p><div className="mt-2 flex items-center justify-between text-[11px] text-sidebar-foreground/50"><span>{item.officer}</span><span>{item.updated}</span></div></button>)}</div>
          <div className="border-t border-sidebar-border p-3"><button className="flex w-full items-center gap-2 rounded-md px-2 py-2 text-xs text-sidebar-foreground/60 hover:bg-sidebar-accent"><Archive size={14} /> Archived cases <ChevronRight className="ml-auto" size={13} /></button></div>
        </aside>
        <section className="flex min-w-0 flex-1 flex-col">
          <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
            <div className="min-w-0 flex-1 border-b border-border/70 lg:border-b-0 lg:border-r"><div className="border-b border-border/70 px-5 py-5 md:px-8"><div className="mb-4 flex items-center gap-2 font-mono text-[10px] font-bold tracking-[0.16em] text-muted-foreground"><span>{selected.id}</span><span className="text-border">/</span><span className="text-emerald-600">{selected.status}</span></div><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight md:text-3xl">{selected.title}</h1><p className="mt-2 text-sm text-muted-foreground">{selected.officer} · {selected.location}</p></div><button className="rounded-md border border-border p-2 text-muted-foreground hover:bg-muted" aria-label="More case actions"><MoreHorizontal size={17} /></button></div></div><div className="space-y-6 p-5 md:p-8"><div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-3"><Info label="Priority" value={selected.priority} /><Info label="Scene" value="North Harbor" /><Info label="Evidence" value="12 items" /></div><div className="rounded-lg border border-border bg-card p-5"><div className="mb-3 flex items-center gap-2 text-xs font-semibold"><Radio size={15} className="text-primary" /> Field brief</div><p className="text-sm leading-6 text-muted-foreground">The eve agent is monitoring the incident record, preparing scene context, and will surface relevant details as you speak. You can keep your attention on the scene.</p></div><div><div className="mb-4 flex items-center justify-between"><h2 className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Agent activity</h2><span className="font-mono text-[10px] text-muted-foreground/60">LIVE TRACE</span></div><div className="relative ml-2 border-l border-border pl-6">{activity.map((item) => <div key={item.time} className="relative pb-6 last:pb-0"><span className={`absolute -left-[31px] top-1.5 flex size-2.5 rounded-full border-2 border-background ${item.tone === 'live' ? 'bg-emerald-500 ring-4 ring-emerald-500/10' : item.tone === 'amber' ? 'bg-amber-500' : 'bg-muted-foreground/40'}`} /><div className="flex items-start gap-3"><item.icon size={15} className={item.tone === 'live' ? 'text-emerald-600' : item.tone === 'amber' ? 'text-amber-600' : 'text-muted-foreground'} /><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{item.label}</p><span className="font-mono text-[10px] text-muted-foreground/60">{item.time}</span></div><p className="mt-1 text-xs text-muted-foreground">{item.detail}</p></div></div></div>)}</div></div></div></div>
            <div className="flex w-full shrink-0 flex-col bg-muted/20 lg:w-[410px] xl:w-[470px]"><div className="border-b border-border/70 bg-card/70 px-5 py-4"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Sparkles size={15} className="text-primary" /><h2 className="text-sm font-semibold">eve field companion</h2></div><p className="mt-1 text-xs text-muted-foreground">Live voice channel · case grounded</p></div><button className="rounded-md p-2 text-muted-foreground hover:bg-muted" aria-label="Audio settings"><Headphones size={16} /></button></div></div><div className="flex flex-1 flex-col items-center justify-center px-6 py-12 text-center"><div className="relative mb-8"><div className={`absolute inset-[-22px] rounded-full border border-emerald-500/20 ${listening ? 'animate-pulse' : ''}`} /><div className={`absolute inset-[-10px] rounded-full border border-emerald-500/30 ${listening ? 'animate-ping' : ''}`} /><button onClick={() => setListening(!listening)} className={`relative flex size-36 items-center justify-center rounded-full border-4 border-background shadow-2xl transition hover:scale-105 ${listening ? 'bg-emerald-600 text-white' : 'bg-primary text-primary-foreground'}`} aria-label={listening ? 'Pause live listening' : 'Start live listening'}>{listening ? <AudioLines size={42} strokeWidth={1.5} /> : <Mic size={40} strokeWidth={1.5} />}</button></div><p className="text-sm font-semibold">{listening ? 'Listening to officer' : 'Voice session paused'}</p><p className="mt-2 max-w-[260px] text-xs leading-5 text-muted-foreground">{listening ? 'Speak naturally. eve will prepare context, call tools, and respond when needed.' : 'Tap the microphone to resume the live field channel.'}</p><div className="mt-10 flex items-center gap-3 rounded-full border border-border bg-card px-4 py-2.5 text-xs text-muted-foreground"><Volume2 size={14} className="text-primary" /> Voice model ready <span className="text-border">·</span> GPT live</div></div><div className="border-t border-border/70 bg-card/70 p-4"><div className="flex items-center justify-between text-[10px] uppercase tracking-[0.14em] text-muted-foreground"><span>Background tasks</span><span className="flex items-center gap-1.5 text-emerald-600"><Circle className="fill-current" size={6} /> 2 running</span></div><div className="mt-3 flex items-center gap-2 rounded-md border border-border bg-background px-3 py-2.5"><Command size={14} className="text-muted-foreground" /><p className="text-xs text-muted-foreground">Evidence map and timeline review</p><Activity className="ml-auto text-primary" size={14} /></div></div></div>
          </div>
        </section>
      </div>
    </main>
  )
}

function Info({ label, value }: { label: string; value: string }) { return <div className="bg-card p-3.5"><p className="mb-2 text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="text-xs font-semibold">{value}</p></div> }
